name: Releases

on: 
  push:
    branches:
    - 'master'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update
    - run: sudo apt install -yy imagemagick zip
    - run: ./build-release.sh
    - run: echo "tag=nightly-$(date -u '+%Y%m%d-%H%M')" >> "$GITHUB_ENV"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/holostreetsLaTeX-overleaf.zip"
        prerelease: false
        body: "Prerelease build of Holostreets LaTeX"
        commit: "master"
        tag: ${{ env.tag }}
        makeLatest: true
